# Generated by Django 4.1.1 on 2022-10-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountYandexDirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_yandex_direct', models.TextField()),
                ('login_yandex_direct', models.CharField(max_length=35)),
                ('account_name', models.CharField(help_text='Введите название аккаунта', max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='BotData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messengers_name', models.CharField(help_text='введите название мессанджера ', max_length=35)),
                ('bot_username', models.CharField(help_text='введите имя бота ', max_length=35)),
                ('token_bot', models.TextField()),
            ],
        ),
    ]
